---
- name: Setup Jenkins Master
  hosts: jvm
  become: true
  vars:
    jenkins_hostname: jvm
    java_packages:
      - java-11-openjdk-devel.x86_64
      
    jenkins_admin_username: ddelsizov
    jenkins_admin_password: secretpassword
    jenkins_plugins_install_dependencies: true
    jenkins_plugins:
    - ssh
    - docker-plugin
    - git

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
      
- name: Add Jenkins slave and vagrant credentials via cli
  hosts: jvm
  tasks:
    - name: Run script
      shell: /vagrant/credential.sh
 
- name: Add job for slave
  hosts: jvm
  tasks:
    - name: Run script
      shell: /vagrant/createjob.sh